apiVersion: v1
kind: Service
metadata:
  name: notificationservice
  namespace: e-commerce
spec:
  selector:
    app: notificationservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP