apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: e-commerce
spec:
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP