apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deployment
  namespace: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image:  orderservice:1.0
        ports:
        - containerPort: 8081
        env:
        - name: ORDERSERVICE
          valueFrom:
            configMapKeyRef:
              name: orderservice-config
        resources:
          limits:
            memory: 128Mi
          requests:
            memory: 128Mi