apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvclaim
  namespace: e-commerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs