apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvclaim
  namespace: e-commerce
spec:
  labels:
    name: mongo_data-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs
spec:
  labels:
    name: mongo_config-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs