apiVersion: v1
kind: Service
metadata:
  name: productcatalog
  namespace: e-commerce
spec:
  selector:
    app: productcatalog
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP